"""Data‑ingestion pipeline — reads ``complaints 2.csv``, applies stratified
sampling, and populates the pgvector embedding tables inside PostgreSQL.

Embeddings are generated by the configured model (default: free local
HuggingFace BAAI/bge‑small‑en‑v1.5 — zero cost).

Usage
─────
    # Stratified sample of 50 000 complaints (recommended default)
    python -m app.retrieval.ingest --sample 50000

    # Smaller dev run
    python -m app.retrieval.ingest --sample 5000

    # Full ingestion (all ~6 M narratives — only if you have time + disk)
    python -m app.retrieval.ingest --no-sample

    # Switch to OpenAI embeddings (paid)
    EMBEDDING_PROVIDER=openai python -m app.retrieval.ingest --sample 50000

Stratified Sampling Strategy
────────────────────────────
Instead of taking the first N rows (biased by date / order), we sample
proportionally across **product × issue** strata so every complaint type
is represented in the vector index.  This gives far better RAG coverage
with far fewer embeddings.

Cost Breakdown (50 000 docs, default local model)
──────────────────────────────────────────────────
  Embedding cost:      $0.00  (runs on CPU, no API calls)
  Postgres storage:    ~200 MB (384‑dim float vectors + metadata)
  Time:                ~10 min on a laptop
"""

from __future__ import annotations

import csv
import logging
import random
from collections import defaultdict
from pathlib import Path
from typing import Optional

from langchain_core.documents import Document

from app.db.session import init_db
from app.retrieval.complaint_index import ComplaintIndex
from app.retrieval.resolution_index import ResolutionIndex
from app.utils.pii import redact_pii

logger = logging.getLogger(__name__)

# Default location of the CFPB dataset
DEFAULT_CSV = Path(__file__).resolve().parent.parent.parent / "complaints.csv"

# ── Column mappings (CFPB dataset) ───────────────────────────────────────────
COL_NARRATIVE = "Consumer complaint narrative"
COL_PRODUCT = "Product"
COL_SUB_PRODUCT = "Sub-product"
COL_ISSUE = "Issue"
COL_SUB_ISSUE = "Sub-issue"
COL_COMPANY = "Company"
COL_STATE = "State"
COL_ZIP = "ZIP code"
COL_SUBMITTED_VIA = "Submitted via"
COL_RESPONSE = "Company response to consumer"
COL_COMPLAINT_ID = "Complaint ID"
COL_DATE_RECEIVED = "Date received"
COL_COMPANY_PUBLIC_RESPONSE = "Company public response"

# Minimum narrative length to be useful for embedding
MIN_NARRATIVE_LENGTH = 30

# How many documents to embed + INSERT per batch
BATCH_SIZE = 500

# Default stratified sample size (good coverage vs. cost tradeoff)
DEFAULT_SAMPLE_SIZE = 50000


# ═════════════════════════════════════════════════════════════════════════════
#  STRATIFIED SAMPLING
# ═════════════════════════════════════════════════════════════════════════════


def _collect_stratified_sample(
    csv_path: Path,
    sample_size: int,
    seed: int = 42,
) -> list[dict]:
    """Scan the CSV and return a stratified sample of rows with narratives.

    Strategy
    ────────
    1. First pass: bucket every row that has a narrative by its
       ``(Product, Issue)`` stratum key.
    2. Allocate sample budget proportionally to each stratum
       (with a minimum of 1 per stratum so rare categories aren't lost).
    3. Randomly sample within each stratum.

    This guarantees that the vector index covers the full diversity of
    complaint types, not just the most common ones.
    """
    logger.info(
        "Collecting stratified sample of %d from %s …", sample_size, csv_path
    )

    strata: dict[tuple[str, str], list[dict]] = defaultdict(list)
    rows_scanned = 0

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows_scanned += 1
            narrative = (row.get(COL_NARRATIVE) or "").strip()
            if len(narrative) < MIN_NARRATIVE_LENGTH:
                continue

            key = (
                row.get(COL_PRODUCT, "unknown"),
                row.get(COL_ISSUE, "unknown"),
            )
            strata[key].append(row)

            # Progress every 500 k rows
            if rows_scanned % 500_000 == 0:
                logger.info(
                    "  scan progress: %d rows, %d strata, %d with narrative",
                    rows_scanned,
                    len(strata),
                    sum(len(v) for v in strata.values()),
                )

    total_with_narrative = sum(len(v) for v in strata.values())
    logger.info(
        "Scan complete: %d rows scanned, %d with narrative, %d strata",
        rows_scanned,
        total_with_narrative,
        len(strata),
    )

    # ── Proportional allocation with minimum guarantee ───────────────────
    rng = random.Random(seed)
    sampled: list[dict] = []

    # Guarantee at least 1 per stratum
    min_per_stratum = 1
    guaranteed = min(min_per_stratum * len(strata), sample_size)
    remaining_budget = sample_size - guaranteed

    for key, rows in strata.items():
        # Guaranteed minimum
        n_guaranteed = min(min_per_stratum, len(rows))
        # Proportional share of remaining budget
        proportion = len(rows) / total_with_narrative
        n_proportional = int(remaining_budget * proportion)
        n_total = min(n_guaranteed + n_proportional, len(rows))

        sampled.extend(rng.sample(rows, k=n_total))

    # If we're under budget (due to rounding), top up from largest strata
    if len(sampled) < sample_size:
        deficit = sample_size - len(sampled)
        sampled_ids = {id(r) for r in sampled}
        pool = [
            r for rows in strata.values() for r in rows if id(r) not in sampled_ids
        ]
        if pool:
            sampled.extend(rng.sample(pool, k=min(deficit, len(pool))))

    # Shuffle so batches aren't all from the same stratum
    rng.shuffle(sampled)

    logger.info(
        "Stratified sample: %d rows across %d strata (from %d total with narrative)",
        len(sampled),
        len(strata),
        total_with_narrative,
    )
    return sampled


# ═════════════════════════════════════════════════════════════════════════════
#  DOCUMENT BUILDERS
# ═════════════════════════════════════════════════════════════════════════════


def _row_to_complaint_doc(row: dict) -> Optional[Document]:
    """Convert a CSV row into a LangChain Document for the complaint index."""
    narrative = (row.get(COL_NARRATIVE) or "").strip()
    if len(narrative) < MIN_NARRATIVE_LENGTH:
        return None

    narrative = redact_pii(narrative)

    page_content = (
        f"Product: {row.get(COL_PRODUCT, 'N/A')}\n"
        f"Issue: {row.get(COL_ISSUE, 'N/A')}\n"
        f"Narrative: {narrative}"
    )

    metadata = {
        "complaint_id": row.get(COL_COMPLAINT_ID, ""),
        "product": row.get(COL_PRODUCT, ""),
        "sub_product": row.get(COL_SUB_PRODUCT, ""),
        "issue": row.get(COL_ISSUE, ""),
        "sub_issue": row.get(COL_SUB_ISSUE, ""),
        "company": row.get(COL_COMPANY, ""),
        "state": row.get(COL_STATE, ""),
        "zip_code": row.get(COL_ZIP, ""),
        "date_received": row.get(COL_DATE_RECEIVED, ""),
        "submitted_via": row.get(COL_SUBMITTED_VIA, ""),
        "source": "complaints_2_csv",
    }
    return Document(page_content=page_content, metadata=metadata)


def _row_to_resolution_doc(row: dict) -> Optional[Document]:
    """Convert a CSV row into a LangChain Document for the resolution index."""
    narrative = (row.get(COL_NARRATIVE) or "").strip()
    response = (row.get(COL_RESPONSE) or "").strip()
    if len(narrative) < MIN_NARRATIVE_LENGTH or not response:
        return None

    narrative = redact_pii(narrative)

    company_public = (row.get(COL_COMPANY_PUBLIC_RESPONSE) or "").strip()

    page_content = (
        f"Product: {row.get(COL_PRODUCT, 'N/A')}\n"
        f"Issue: {row.get(COL_ISSUE, 'N/A')}\n"
        f"Narrative: {narrative}\n"
        f"Resolution: {response}"
    )
    if company_public:
        page_content += f"\nCompany response: {company_public}"

    metadata = {
        "complaint_id": row.get(COL_COMPLAINT_ID, ""),
        "product": row.get(COL_PRODUCT, ""),
        "issue": row.get(COL_ISSUE, ""),
        "company": row.get(COL_COMPANY, ""),
        "resolution_outcome": response,
        "date_received": row.get(COL_DATE_RECEIVED, ""),
        "source": "complaints_2_csv",
    }
    return Document(page_content=page_content, metadata=metadata)


# ═════════════════════════════════════════════════════════════════════════════
#  MAIN INGESTION
# ═════════════════════════════════════════════════════════════════════════════


def ingest_csv(
    csv_path: Path = DEFAULT_CSV,
    sample_size: Optional[int] = DEFAULT_SAMPLE_SIZE,
    batch_size: int = BATCH_SIZE,
    seed: int = 42,
) -> dict[str, int]:
    """Read the CFPB complaints CSV and populate both pgvector tables.

    Parameters
    ──────────
    csv_path : Path
        Path to the complaints CSV file.
    sample_size : int, optional
        Number of complaints to ingest via stratified sampling.
        Set to ``None`` to ingest ALL rows (not recommended unless needed).
        Default: 50 000 — provides excellent RAG coverage at zero
        embedding cost with the local model.
    batch_size : int
        Number of documents to embed + INSERT per batch.
    seed : int
        Random seed for reproducible stratified sampling.

    Returns
    ───────
    dict with keys: complaint_docs, resolution_docs, rows_sampled, strata
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    # Ensure pgvector extension + tables exist
    logger.info("Initialising database (pgvector extension + tables)…")
    init_db()

    # ── Collect sample ───────────────────────────────────────────────────
    if sample_size is not None:
        rows = _collect_stratified_sample(csv_path, sample_size, seed=seed)
    else:
        # Full scan — read all rows with narratives
        logger.info("No sampling — reading ALL rows with narratives…")
        rows = []
        with open(csv_path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                narrative = (row.get(COL_NARRATIVE) or "").strip()
                if len(narrative) >= MIN_NARRATIVE_LENGTH:
                    rows.append(row)

    # ── Build documents and ingest in batches ────────────────────────────
    complaint_idx = ComplaintIndex()
    resolution_idx = ResolutionIndex()

    complaint_batch: list[Document] = []
    resolution_batch: list[Document] = []
    total_complaint = 0
    total_resolution = 0

    for i, row in enumerate(rows):
        c_doc = _row_to_complaint_doc(row)
        if c_doc is not None:
            complaint_batch.append(c_doc)
            total_complaint += 1

        r_doc = _row_to_resolution_doc(row)
        if r_doc is not None:
            resolution_batch.append(r_doc)
            total_resolution += 1

        # Flush complaint batch
        if len(complaint_batch) >= batch_size:
            complaint_idx.add_complaints(complaint_batch)
            logger.info(
                "Flushed %d complaint docs → Postgres (total: %d / %d)",
                len(complaint_batch), total_complaint, len(rows),
            )
            complaint_batch = []

        # Flush resolution batch
        if len(resolution_batch) >= batch_size:
            resolution_idx.add_resolutions(resolution_batch)
            logger.info(
                "Flushed %d resolution docs → Postgres (total: %d)",
                len(resolution_batch), total_resolution,
            )
            resolution_batch = []

    # Flush remaining
    if complaint_batch:
        complaint_idx.add_complaints(complaint_batch)
    if resolution_batch:
        resolution_idx.add_resolutions(resolution_batch)

    stats = {
        "rows_sampled": len(rows),
        "complaint_docs": total_complaint,
        "resolution_docs": total_resolution,
    }
    logger.info("Ingestion complete: %s", stats)
    return stats


# ═════════════════════════════════════════════════════════════════════════════
#  CLI ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import argparse

    from app.retrieval.embeddings import EMBEDDING_PROVIDER, get_embedding_dim
    from app.observability.logging import setup_logging

    setup_logging("INFO")

    parser = argparse.ArgumentParser(
        description="Ingest complaints CSV into PostgreSQL + pgvector"
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=DEFAULT_CSV,
        help=f"Path to complaints CSV (default: {DEFAULT_CSV})",
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=DEFAULT_SAMPLE_SIZE,
        help=(
            f"Stratified sample size (default: {DEFAULT_SAMPLE_SIZE:,}). "
            "Use --no-sample to ingest everything."
        ),
    )
    parser.add_argument(
        "--no-sample",
        action="store_true",
        help="Ingest ALL rows with narratives (no sampling)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=BATCH_SIZE,
        help=f"Documents per embedding batch (default: {BATCH_SIZE})",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible sampling (default: 42)",
    )
    args = parser.parse_args()

    sample = None if args.no_sample else args.sample

    print(f"╔══════════════════════════════════════════════════════════════╗")
    print(f"║  Complaint Ingestion Pipeline                              ║")
    print(f"╠══════════════════════════════════════════════════════════════╣")
    print(f"║  Embedding provider : {EMBEDDING_PROVIDER:<38s}║")
    print(f"║  Embedding dim      : {get_embedding_dim():<38d}║")
    print(f"║  Sample size        : {str(sample or 'ALL'):<38s}║")
    print(f"║  Embedding cost     : {'$0.00 (local)' if EMBEDDING_PROVIDER != 'openai' else '~$' + f'{(sample or 6_400_000) * 400 * 0.02 / 1_000_000:.2f} (OpenAI)':<38s}║")
    print(f"╚══════════════════════════════════════════════════════════════╝")
    print()

    stats = ingest_csv(
        csv_path=args.csv,
        sample_size=sample,
        batch_size=args.batch_size,
        seed=args.seed,
    )

    print(f"\n✅  Ingestion complete (PostgreSQL + pgvector):")
    print(f"   Rows sampled:     {stats['rows_sampled']:,}")
    print(f"   Complaint docs:   {stats['complaint_docs']:,}")
    print(f"   Resolution docs:  {stats['resolution_docs']:,}")
    print(f"   Embedding cost:   $0.00" if EMBEDDING_PROVIDER != "openai" else "")
